{
	"name": "A Link to the Past",
	"author": "SeanCass",
	"platform": "SNES",
	
	"goals": [
		{ "name": "Defeat both Aga 1 and Aga 2 Swordless", "difficulty": 13, "tags": ["KAga12NS", "Mire2NSNFR", "NoSQ"] },
		{ "name": "Defeat Kholdstare with 3 Hearts", "difficulty": 12, "tags": ["KKS3H", "NoMitts", "NoNet"] },
		{ "name": "Open the door to the Desert BK without using your Sword or Bow; Hammer, Fire Rod, Bombs, and either Cane cannot be in your inventory", 
			"difficulty": 11, "tags": ["DesBKnada", "NoNet", "LWBoss3S", "3LWBChests"] },
		{ "name": "Eat apples from 3 different trees without having the Pegasus Boots in your inventory", "difficulty": 11, "tags": ["3ApplesNB", "NoSQ", "NoMitts"] },
		{ "name": "OHKO Ganon fight", "difficulty": 11, "tags": ["Pig"] },
		{ "name": "Complete Tower of Hera swordless", "difficulty": 10, "tags": ["HeraNS", "KAga12NS", "NoSQ", "LWBoss3S", "3LWBChests"] },
		{ "name": "No S+Q (You may die to save, if you die while traveling you must use the nearest place)", "difficulty": 10, "tags": ["NoSQ", "TriFRIR"] },
		{ "name": "Obtain the Mirror Shield without having the Pegasus Boots in your inventory", "difficulty": 10, "tags": ["MirShNB", "3ApplesNB", "NoMitts"] },
		{ "name": "Kill 3 different Gold Knights with a regular bee", "difficulty": 10, "tags": ["3Gold1Bee"] },
		{ "name": "Open the Door in the 5 Pengator Room just after IPBJ, but only when your Sword/Shield/Armor are different levels", "difficulty": 10, "tags": ["5PengDLE", "YHYSYS"] },
		{ "name": "Defeat Eastern Palace's Armos Knights with an item you may only find in the Dark World", "difficulty": 10, "tags": ["ArmosDWW", "Kb4Esc", "Arm2CoS"] },
		{ "name": "Obtain the Gold Sword Twice", "difficulty": 10, "tags": ["GSTwice"] },
		{ "name": "Defeat Agahnim swordless", "difficulty": 10, "tags": ["AgaNS", "KAga12NS"] },
		{ "name": "Finish Misery Mire damageless", "difficulty": 9, "tags": ["OHKOMire"] },
		{ "name": "Yellow Sword, Yellow Hat & Yellow Shield", "difficulty": 9, "tags": ["YHYSYS", "5PengDLE"] },
		{ "name": "Slay Agahnim 2 with the Blue Mail equipped and Kholdstare with the Red Mail equipped", "difficulty": 9, "tags": ["A2BKR", "NoSQ"] },
		{ "name": "Collect a Green Rupee, a Blue Rupee, a Red Rupee, 50 Rupees, 100 Rupees, and 300 Rupees from depletable small chests", "difficulty": 9, "tags": ["ChestQuest", "NoSQ"] },
		{ "name": "Defeat Ganon", "difficulty": 9, "tags": ["Pig"] },
		{ "name": "Make 9 Fairies appear in 1 Room all at once", "difficulty": 9, "tags": ["9Fairy", "NoNet"] },
		{ "name": "No Titan's Mitts", "difficulty": 9, "tags": ["NoMitts", "KAga12NS", "Mitts2Pow"] },
		{ "name": "Defeat Vitreous swordless", "difficulty": 9, "tags": ["VittyNS", "KAga12NS"] },
		{ "name": "Defeat each of the Light World bosses with a different Sword", "difficulty": 9, "tags": ["LWBoss3S", "KAga12NS", "HeraNS", "3LWBChests"] },
		{ "name": "Clear the 2nd Room of Misery Mire Swordless, without the Fire Rod in your inventory", "difficulty": 9, "tags": ["Mire2NSNFR", "KAga12NS"] },
		{ "name": "Open the Ice Rod Cave with 0 Rupees/Arrows/Bombs in HUD (Obv can't expend your last bomb so your HUD says 000, 0, 0)", "difficulty": 9, "tags": ["IRCaveHUD"] },
		{ "name": "Complete Tower of Hera with the Red Walls down on the 3rd floor at all times, you may not step on star tiles", "difficulty": 9, "tags": ["RedWallHera"] },
		{ "name": "Defeat Ice Armos using a different item to damage each of them", "difficulty": 9, "tags": ["Arm26Weaps", "NoSQ", "Arm2CoS", "Arm2MSs"] },
		{ "name": "Ice Palace 100% map completion", "difficulty": 9, "tags": ["Ice100", "PoD100", "Skull100", "Mire100", "TRock100", "GTower100"] },
		{ "name": "Defeat Moldorm 1 & Moldorm 2 with the Fighter Sword", "difficulty": 9, "tags": ["Mold12FS", "KAga12NS", "NoSQ"] },
		{ "name": "Kill all the Red and Green Mimics in Palace of Darkness with the Silver Arrows", "difficulty": 9, "tags": ["MimicsSA", "NoSQ"] },
		{ "name": "Slay all 6 unique Stalfos variations", "difficulty": 9, "tags": [] },
		{ "name": "Defeat Mothula with the Golden Sword", "difficulty": 9, "tags": ["MothGS", "NoNet"] },
		{ "name": "Kill Trinexx heads with Firerod and Icerod only", "difficulty": 9, "tags": ["TriFRIR", "NoSQ"] },
		{ "name": "Defeat Armos 2 only using Master Sword slashes", "difficulty": 9, "tags": ["Arm2MSs", "NoSQ", "Arm2CoS", "Arm26Weaps"] },
		{ "name": "Misery Mire 100% map completion", "difficulty": 9, "tags": ["Mire100", "PoD100", "Skull100", "Ice100", "TRock100", "GTower100"] },
		{ "name": "Get the Power Gloves without the Desert Palace Big Key", "difficulty": 9, "tags": ["PGwTTBK"] },
		{ "name": "9 Compasses", "difficulty": 9, "tags": ["9Comps", "10BChest", "10Maps"] },
		{ "name": "Defeat any boss before finishing escape", "difficulty": 9, "tags": ["Kb4Esc", "ArmosDWW", "SahasX"] },
		{ "name": "Defeat Lanmolas 1 with the Cane of Byrna & Lanmolas 2 with the Cane of Somaria", "difficulty": 9, "tags": ["Lan12Canes", "Lan1IR"] },
		{ "name": "Collect the Cane of Byrna while only having 4 Hearts", "difficulty": 9, "tags": ["Byrna4H", "NoSQ"] },
		{ "name": "Open 10 big chests", "difficulty": 9, "tags": ["10BChest", "10Maps", "9Comps"] },
		{ "name": "Collect Blue Floor Rupees from 4 Rooms", "difficulty": 9, "tags": ["4BFMoney"] },
		{ "name": "Turtle Rock 100% map completion", "difficulty": 8, "tags": ["TRock100", "PoD100", "Skull100", "Ice100", "Mire100", "GTower100"] },
		{ "name": "10 Maps", "difficulty": 8, "tags": ["10Maps", "9Comps", "10BChest"] },
		{ "name": "Ganon's Tower 100% map completion", "difficulty": 8, "tags": ["GT100", "KAga12NS", "PoD100", "Skull100", "Ice100", "Mire100", "TRock100"] },
		{ "name": "Open the 3 Big Chests in Light World dungeons in reverse order", "difficulty": 8, "tags": ["3LWBChests", "DesBKnada"] },
		{ "name": "Obtain all level 2 items: Master Sword, Blue Mail, Fire Shield, Magic Boomerang, Powder, Titan's Mitts, Silver Arrows & Flute", 
			"difficulty": 8, "tags": ["Lv2Eq", "NoMitts"] },
		{ "name": "2 Canes, 3 Medallions, 4 Bottles", "difficulty": 8, "tags": ["2C3M4B", "MagicEq"] },
		{ "name": "Open the closed door in the Red Horsehead, Blue Horsehead, and Red Stalfos Room in Thieves Town with a medallion ONLY", "difficulty": 8, "tags": ["TTBombos"] },
		{ "name": "Defeat Arrghus without having the Pegasus Boots in your inventory", "difficulty": 8, "tags": ["ArgNB", "AEqL2R"] },
		{ "name": "Complete the A items inventory from right to left", "difficulty": 8, "tags": ["AEqL2R", "3ApplesNB"] },
		{ "name": "Pay 5 NPCs for a gameplay tip", "difficulty": 8, "tags": ["Pay54tip", "NoMitts"] },
		{ "name": "Complete Palace of Darkness & Skull Woods without pushing any statues", "difficulty": 8, "tags": ["PoDSkNStat", "NoSQ"] },
		{ "name": "Open 15 Chests inside Death Mountain Caves ", "difficulty": 8, "tags": ["15ChestDM"] },
		{ "name": "Fill 4 bottles with 4 unique things, you may not enter the Witch's Hut", "difficulty": 8, "tags": ["4BotsNHut", "4BluePot", "4Bots4Reds"] },
		{ "name": "Fill 4 Bottles up with Red Potions from 4 different shops (excluding the potion shop)", 
			"difficulty": 8, "tags": ["4Bots4Reds", "999", "70Arrows", "50Bombs", "4BluePot", "4BotsNHut"] },
		{ "name": "Complete 4 columns in your Y items inventory", "difficulty": 8, "tags": ["Y4Cols"] },
		{ "name": "Skull Woods 100% map completion", "difficulty": 8, "tags": ["Skull100", "PoD100", "Ice100", "Mire100", "TRock100", "GTower100"] },
		{ "name": "Dark Palace 100% map completion", "difficulty": 8, "tags": ["PoD100", "NoSQ", "Skull100", "Ice100", "Mire100", "TRock100", "GTower100"] },
		{ "name": "Defeat 3 Lynels without using your Sword or Hammer", "difficulty": 8, "tags": ["3LynelNSNH"] },
		{ "name": "Blow up the entrance to the Pyramid Fairy Fountain", "difficulty": 7, "tags": ["SupaBom"] },
		{ "name": "Deliver the final blow with a bomb on 2 different bosses", "difficulty": 7, "tags": ["2BosswBomb"] },
		{ "name": "4 Blue Potions", "difficulty": 7, "tags": ["4BluePot", "999", "70Arrows", "50Bombs", "4Bots4Reds", "4BotsNHut"] },
		{ "name": "Defeat Ice Armos using the Cane of Somaria", "difficulty": 7, "tags": ["Arm2CoS", "NoSQ", "Arm26Weaps", "Arm2MSs"] },
		{ "name": "Go through all of the warps to Dark World (9 of them)", "difficulty": 7, "tags": ["9DWWarps", "NoMitts"] },
		{ "name": "You must collect 1 Heart Piece for every Y and A Item (this includes Moon Pearl) you collect ", "difficulty": 7, "tags": ["1Eq1HP", "13H"] },
		{ "name": "Defeat the Black Ball & Chain Guard with both the fighter sword and the gold sword", "difficulty": 7, "tags": ["BnCFSGS"] },
		{ "name": "Collect a fairy 2 unique ways in Kakariko Town without going indoors", "difficulty": 7, "tags": ["NoNet", "2FairyKak"] },
		{ "name": "Win 300 Rupees in a Chest Game", "difficulty": 7, "tags": ["300Rupees"] },
		{ "name": "4 Crystals", "difficulty": 7, "tags": ["4Crys"] },
		{ "name": "Defeat Trinexx equipped with the Master Sword", "difficulty": 7, "tags": ["TriMS"] },
		{ "name": "Have the 'X' appear on Sahrashala's Hideout before completing Eastern Palace", "difficulty": 7, "tags": ["SahasX", "Kb4Esc"] },
		{ "name": "Get the Blue Boomerang after slaying Agahnim 1", "difficulty": 7, "tags": ["Boomb4Aga1"] },
		{ "name": "999 Rupees", "difficulty": 6, "tags": ["999", "70Arrows", "50Bombs", "4BluePot", "4Bots4Reds"] },
		{ "name": "50 Bombs", "difficulty": 6, "tags": ["50bombs", "999", "70Arrows", "4BluePot", "4Bots4Reds"] },
		{ "name": "70 Arrows", "difficulty": 6, "tags": ["70Arrows", "999", "50Bombs", "4BluePot", "4Bots4Reds"] },
		{ "name": "Kill a boss with at least 3 small keys in your inventory", "difficulty": 6, "tags": ["1Boss3Key", "NoSQ"] },
		{ "name": "Open 12 small chests containing a red rupee outside of Dark & Light Kakariko ", "difficulty": 6, "tags": ["12RRups"] },
		{ "name": "Collect the lumberjacks Heart Piece and the digging game Heart Piece", "difficulty": 6, "tags": ["LJDigHPs"] },
		{ "name": "Do 20 chest turns", "difficulty": 5, "tags": ["20turns"] },
		{ "name": "Defeat Arrghus' puffs and Arrghus with the Ice Rod+Hookshot", "difficulty": 5, "tags": ["ArgIR"] },
		{ "name": "Open the door in the 3 Blue Beetle Room in Tower of Hera Swordless, using SPECIFICALLY the Cane of Somaria and nothing else", "difficulty": 5, "tags": ["HeraCoS"] },
		{ "name": "Downgrade Titan's Mitts to Power Gloves", "difficulty": 5, "tags": ["Mitts2Pow", "NoMitts"] },
		{ "name": "Collect every item that consumes Magic", "difficulty": 5, "tags": ["MagicEq", "2C3M4B"] },
		{ "name": "13 Hearts", "difficulty": 5, "tags": ["13H", "1Eq1HP"] },
		{ "name": "Get a perfect score in the Shooting Gallery", "difficulty": 4, "tags": ["WilliamTell"] },
		{ "name": "Defeat Lanmolas 1 with the Ice Rod", "difficulty": 4, "tags": ["Lan1IR", "Lan12Canes"] },
		{ "name": "Communicate with 10 telepathic tiles", "difficulty": 4, "tags": ["10Tiles"] },
		{ "name": "No Bug Net", "difficulty": 3, "tags": ["NoNet", "3Gold1Bee"] },
		{ "name": "Obtain 1/2 Magic", "difficulty": 2, "tags": ["HalfMag"] }
	],
	
	"tags": {},
	
	"modifiers": {}
}