{
	"name": "Lunar Pool",
	"platform": "NES",
	
	"goals": [
		{ "name": "Stage 01", "difficulty":  1 },
		{ "name": "Stage 02", "difficulty":  2 },
		{ "name": "Stage 03", "difficulty":  3 },
		{ "name": "Stage 04", "difficulty":  4 },
		{ "name": "Stage 05", "difficulty":  5 },
		{ "name": "Stage 06", "difficulty":  6 },
		{ "name": "Stage 07", "difficulty":  7 },
		{ "name": "Stage 08", "difficulty":  8 },
		{ "name": "Stage 09", "difficulty":  9 },
		{ "name": "Stage 10", "difficulty": 10 },
		{ "name": "Stage 11", "difficulty": 11 },
		{ "name": "Stage 12", "difficulty": 12 },
		{ "name": "Stage 13", "difficulty": 13 },
		{ "name": "Stage 14", "difficulty": 14 },
		{ "name": "Stage 15", "difficulty": 15 },
		{ "name": "Stage 16", "difficulty": 16 },
		{ "name": "Stage 17", "difficulty": 17 },
		{ "name": "Stage 18", "difficulty": 18 },
		{ "name": "Stage 19", "difficulty": 19 },
		{ "name": "Stage 20", "difficulty": 20 },
		{ "name": "Stage 21", "difficulty": 21 },
		{ "name": "Stage 22", "difficulty": 22 },
		{ "name": "Stage 23", "difficulty": 23 },
		{ "name": "Stage 24", "difficulty": 24 },
		{ "name": "Stage 25", "difficulty": 25 },
		{ "name": "Stage 26", "difficulty": 26 },
		{ "name": "Stage 27", "difficulty": 27 },
		{ "name": "Stage 28", "difficulty": 28 },
		{ "name": "Stage 29", "difficulty": 29 },
		{ "name": "Stage 30", "difficulty": 30 },
		{ "name": "Stage 31", "difficulty": 31 },
		{ "name": "Stage 32", "difficulty": 32 },
		{ "name": "Stage 33", "difficulty": 33 },
		{ "name": "Stage 34", "difficulty": 34 },
		{ "name": "Stage 35", "difficulty": 35 },
		{ "name": "Stage 36", "difficulty": 36 },
		{ "name": "Stage 37", "difficulty": 37 },
		{ "name": "Stage 38", "difficulty": 38 },
		{ "name": "Stage 39", "difficulty": 39 },
		{ "name": "Stage 40", "difficulty": 40 },
		{ "name": "Stage 41", "difficulty": 41 },
		{ "name": "Stage 42", "difficulty": 42 },
		{ "name": "Stage 43", "difficulty": 43 },
		{ "name": "Stage 44", "difficulty": 44 },
		{ "name": "Stage 45", "difficulty": 45 },
		{ "name": "Stage 46", "difficulty": 46 },
		{ "name": "Stage 47", "difficulty": 47 },
		{ "name": "Stage 48", "difficulty": 48 },
		{ "name": "Stage 49", "difficulty": 49 },
		{ "name": "Stage 50", "difficulty": 50 },
		{ "name": "Stage 51", "difficulty": 51 },
		{ "name": "Stage 52", "difficulty": 52 },
		{ "name": "Stage 53", "difficulty": 53 },
		{ "name": "Stage 54", "difficulty": 54 },
		{ "name": "Stage 55", "difficulty": 55 },
		{ "name": "Stage 56", "difficulty": 56 },
		{ "name": "Stage 57", "difficulty": 57 },
		{ "name": "Stage 58", "difficulty": 58 },
		{ "name": "Stage 59", "difficulty": 59 },
		{ "name": "Stage 60", "difficulty": 60 }
	],
	
	"modifiers": {
		"@required": true,
		"*": [
			{ "name": "Friction = 8", "difficulty": 10 },
			{ "name": "Friction = 16", "difficulty": 5 },
			{ "name": "Friction = 32", "difficulty": 0 },
			{ "name": "Friction = 64", "difficulty": 3 },
			{ "name": "Friction = 128", "difficulty": 6 }
		]
	}
}