{
	"name": "Yooka-Laylee",
	"author": "Forstride",
	"platform": "PC/PS4/Xbox One/Switch",
	
	"rules": [
		"Timer starts when pressing A to start a new file.",
		"Timer ends when you complete a row/column/diagonal.",
		"Co-op is not allowed."],
	
	"goals": [
		{ "name": "Clara's Pagie in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Duke's Pagie in TT", "difficulty": 3, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Blastooie's Pagie in TT", "difficulty": 5, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Knights of Hamalot Pagie in TT", "difficulty": 2, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Bush Pagie in TT", "difficulty": 4, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Shovel Knight's Pagie in TT", "difficulty": 2, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Rings Challenge Pagie in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Tile Puzzle Pagie in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Planker's Pagie in TT", "difficulty": 3, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Pagie Piece Pagie in TT", "difficulty": 2, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Normal Nimble Race Pagie in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Icy Nimble Race Pagie in TT", "difficulty": 3, "tags": ["Tribalstack Tropics", "Pagies"] },
		{ "name": "Mr. Blowy's Pagie in TT", "difficulty": 3, "tags": ["Tribalstack Tropics", "Pagies"] },
		
		{ "name": "Rings Challenge Pagie in GGG", "difficulty": 1, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Musical Crystals Pagie in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Capital B Snowman Pagie in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Snowmen Pagie in GGG", "difficulty": 4, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Tubbz Pagie in GGG", "difficulty": 7, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Trivia Pagie in GGG", "difficulty": 4, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Clara's Pagie in GGG", "difficulty": 3, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Gloomy Gem Grotto Pagie in GGG", "difficulty": 3, "tags": ["Glitterglaze Glacier", "Pagies"] },
		{ "name": "Moving Walls Pagie in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Pagies"] },
		
		{ "name": "Jack-O'-Lantern's Pagie in MMM", "difficulty": 1, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Underwater Thorns Pagie in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Swampy Station Pagie in MMM", "difficulty": 4, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Pumping Plant Pagie in MMM", "difficulty": 1, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Cage Arena Pagie in MMM", "difficulty": 2, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Hotswitch Hollow Pagie in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Wally's Pagie in MMM", "difficulty": 1, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Ollie's Maze Pagie in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Dolly's Pagie in MMM", "difficulty": 4, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Jolly's Pagie in MMM", "difficulty": 2, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Clara's Pagie in MMM", "difficulty": 2, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Planker's Pagie in MMM", "difficulty": 2, "tags": ["Moodymaze Marsh", "Pagies"] },
		{ "name": "Obstacle Course Pagie in MMM", "difficulty": 2, "tags": ["Moodymaze Marsh", "Pagies"] },
		
		{ "name": "6 OoB Pagies in CC", "difficulty": 3, "tags": ["Capital Cashino", "Pagies"] },
		{ "name": "10 Casino Token Pagie in CC", "difficulty": 1, "tags": ["Capital Cashino", "Pagies"] },
		{ "name": "20 Casino Token Pagie in CC", "difficulty": 2, "tags": ["Capital Cashino", "Pagies"] },
		{ "name": "30 Casino Token Pagie in CC", "difficulty": 3, "tags": ["Capital Cashino", "Pagies"] },
		{ "name": "40 Casino Token Pagie in CC", "difficulty": 4, "tags": ["Capital Cashino", "Pagies"] },
		{ "name": "50 Casino Token Pagie in CC", "difficulty": 5, "tags": ["Capital Cashino", "Pagies"] },
		
		{ "name": "Lighthouse Pagie in GG", "difficulty": 1, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Lunar Lockup Pagie in GG", "difficulty": 2, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Crane Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Black Hole In One Pagie in GG", "difficulty": 4, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Shovel Knight's Pagie in GG", "difficulty": 6, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Ocean Nimble Race Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Pagie Piece Pagie in GG", "difficulty": 2, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Schell's Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Cosmic Cavern Pagie in GG", "difficulty": 1, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Fitness Frog's Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Star Fishing Pagie in GG", "difficulty": 2, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Captain's Pagie in GG", "difficulty": 2, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Rusto Pagie in GG", "difficulty": 2, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Electric Orb Pagie in GG", "difficulty": 4, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Outhouse Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Spacecog Station Pagie in GG", "difficulty": 3, "tags": ["Galleon Galaxy", "Pagies"] },
		{ "name": "Velocity Terminal Pagie in GG", "difficulty": 4, "tags": ["Galleon Galaxy", "Pagies"] },
		
		{ "name": "Blasto's Pagie in HT", "difficulty": 2, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Shipwreck Mast Pagie in HT", "difficulty": 2, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Fire Pipe Pagie in HT", "difficulty": 4, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Novel Hovel Pagie in HT", "difficulty": 3, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Archives Pagie in HT", "difficulty": 2, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Balloons Pagie in HT", "difficulty": 3, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Noveliser 64 Pagie in HT", "difficulty": 2, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Underwater Rings Pagie in HT", "difficulty": 2, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Crazy Kirkhope Pagie in HT", "difficulty": 3, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Toxic Tunnel Pagie in HT", "difficulty": 4, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Wind Tunnel Pagie in HT", "difficulty": 4, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Forcefield Slide Pagie in HT", "difficulty": 5, "tags": ["Hivory Towers", "Pagies"] },
		{ "name": "Broken Arcade Machine Pagie in HT", "difficulty": 3, "tags": ["Hivory Towers", "Pagies"] },
		
		{ "name": "All Ghost Writers in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Ghost Writers"] },
		{ "name": "All Ghost Writers in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Ghost Writers"] },
		{ "name": "All Ghost Writers in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Ghost Writers"] },
		{ "name": "All Ghost Writers in CC", "difficulty": 4, "tags": ["Capital Cashino", "Ghost Writers"] },
		{ "name": "All Ghost Writers in GG", "difficulty": 5, "tags": ["Galleon Galaxy", "Ghost Writers"] },
		
		{ "name": "Health Extender in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Health Extenders"] },
		{ "name": "Health Extender in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Health Extenders"] },
		{ "name": "Health Extender in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Health Extenders"] },
		{ "name": "Health Extender in CC", "difficulty": 4, "tags": ["Capital Cashino", "Health Extenders"] },
		{ "name": "Health Extender in GG", "difficulty": 5, "tags": ["Galleon Galaxy", "Health Extenders"] },
		{ "name": "Health Extender in HT", "difficulty": 1, "tags": ["Hivory Towers", "Health Extenders"] },
		
		{ "name": "Power Extender in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Power Extenders"] },
		{ "name": "Power Extender in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Power Extenders"] },
		{ "name": "Power Extender in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Power Extenders"] },
		{ "name": "Power Extender in CC", "difficulty": 4, "tags": ["Capital Cashino", "Power Extenders"] },
		{ "name": "Power Extender in GG", "difficulty": 5, "tags": ["Galleon Galaxy", "Power Extenders"] },
		{ "name": "Power Extender in HT", "difficulty": 1, "tags": ["Hivory Towers", "Power Extenders"] },
		
		{ "name": "Pirate Treasure in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Pirate Treasures"] },
		{ "name": "Pirate Treasure in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Pirate Treasures"] },
		{ "name": "Pirate Treasure in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Pirate Treasures"] },
		{ "name": "Pirate Treasure in CC", "difficulty": 4, "tags": ["Capital Cashino", "Pirate Treasures"] },
		{ "name": "Pirate Treasure in GG", "difficulty": 5, "tags": ["Galleon Galaxy", "Pirate Treasures"] },
		
		{ "name": "Learn Sonar Shot", "difficulty": 1, "tags": ["Tribalstack Tropics", "Trowzer Moves"] },
		{ "name": "Learn Slurp Shot", "difficulty": 1, "tags": ["Tribalstack Tropics", "Trowzer Moves"] },
		{ "name": "Learn Buddy Slam", "difficulty": 1, "tags": ["Tribalstack Tropics", "Trowzer Moves"] },
		{ "name": "Learn Slurp State", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Trowzer Moves"] },
		{ "name": "Learn Lizard Leap", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Trowzer Moves"] },
		{ "name": "Learn Sonar 'Splosion", "difficulty": 3, "tags": ["Moodymaze Marsh", "Trowzer Moves"] },
		{ "name": "Learn Lizard Lash", "difficulty": 3, "tags": ["Moodymaze Marsh", "Trowzer Moves"] },
		{ "name": "Learn Reptile Rush", "difficulty": 4, "tags": ["Capital Cashino", "Trowzer Moves"] },
		{ "name": "Learn Sonar Shield", "difficulty": 5, "tags": ["Galleon Galaxy", "Trowzer Moves"] },
		
		{ "name": "Complete Kartos Karting", "difficulty": 1, "tags": ["Tribalstack Tropics", "Rextro Minigames"] },
		{ "name": "Complete Glaciators", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Rextro Minigames"] },
		{ "name": "Complete Bee Bop", "difficulty": 3, "tags": ["Moodymaze Marsh", "Rextro Minigames"] },
		{ "name": "Complete Hurdle Hijinx", "difficulty": 4, "tags": ["Capital Cashino", "Rextro Minigames"] },
		{ "name": "Complete Up 'N' Nova", "difficulty": 5, "tags": ["Galleon Galaxy", "Rextro Minigames"] },
		{ "name": "Complete Gun-tlet Run", "difficulty": 1, "tags": ["Hivory Towers", "Rextro Minigames"] },
		{ "name": "Complete Blag the Flag", "difficulty": 1, "tags": ["Hivory Towers", "Rextro Minigames"] },
		{ "name": "Complete Jobstacle Course", "difficulty": 1, "tags": ["Hivory Towers", "Rextro Minigames"] },
		
		{ "name": "Kartos track in TT", "difficulty": 1, "tags": ["Tribalstack Tropics", "Kartos Tracks"] },
		{ "name": "Kartos track in GGG", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Kartos Tracks"] },
		{ "name": "Kartos track in MMM", "difficulty": 3, "tags": ["Moodymaze Marsh", "Kartos Tracks"] },
		{ "name": "Kartos track in CC", "difficulty": 4, "tags": ["Capital Cashino", "Kartos Tracks"] },
		{ "name": "Kartos track in GG", "difficulty": 5, "tags": ["Galleon Galaxy", "Kartos Tracks"] },
		
		{ "name": "Defeat The Great Rampo", "difficulty": 1, "tags": ["Tribalstack Tropics", "Bosses", "The Great Rampo"] },
		{ "name": "Defeat Brrreeze Blok", "difficulty": 2, "tags": ["Glitterglaze Glacier", "Bosses", "Brrreeze Blok"] },
		{ "name": "Defeat Trev the Tenteyecle", "difficulty": 3, "tags": ["Moodymaze Marsh", "Bosses", "Trev the Tenteyecle"] },
		{ "name": "Defeat I.N.E.P.T.", "difficulty": 4, "tags": ["Capital Cashino", "Bosses", "I.N.E.P.T."] },
		{ "name": "Defeat Planette", "difficulty": 5, "tags": ["Galleon Galaxy", "Bosses", "Planette"] },
		{ "name": "Defeat Capital B", "difficulty": 6, "tags": ["Hivory Towers", "Bosses", "Capital B"] },
		
		{ "name": "Destroy all out of order slot machines in CC", "difficulty": 6, "tags": ["Capital Cashino", "Random Goals"] },
		{ "name": "Make Nimbo wet in TT", "difficulty": 3, "tags": ["Tribalstack Tropics", "Random Goals"] },
		{ "name": "Help all 4 Knights of Hamalot in CC", "difficulty": 4, "tags": ["Capital Cashino", "Random Goals"] },
		{ "name": "Complete 5 slot machines in CC", "difficulty": 3, "tags": ["Capital Cashino", "Random Goals"] },
		
	],
	
	"difficulty": {
		"easymax": 3,
		"normmin": 1,
		"normmax": 20,
		"hardmin": 5
	},
	
	"tags": {
		"Tribalstack Tropics": { "allowmultiple": false },
		"Glitterglaze Glacier": { "allowmultiple": false },
		"Moodymaze Marsh": { "allowmultiple": false },
		"Capital Cashino": { "allowmultiple": false },
		"Galleon Galaxy": { "allowmultiple": false },
		"Hivory Towers": { "allowmultiple": true },
			
		"Pagies": { "image": "http://i.imgur.com/CbEp2qu.png" },
		"Ghost Writers": { "image": "http://i.imgur.com/3zwRNNv.png" },
		"Health Extenders": { "image": "http://i.imgur.com/RotvIaA.png" },
		"Power Extenders": { "image": "http://i.imgur.com/7yoKtBJ.png" },
		"Pirate Treasures": { "image": "http://i.imgur.com/ZJQLkjW.png" },
			
		"Trowzer Moves": { "image": "http://i.imgur.com/uGz6jpK.png" },
		"Rextro Minigames": { "image": "http://i.imgur.com/wICXqvP.png" },
		"Kartos Tracks": { "image": "http://i.imgur.com/31cbXMV.png" },
			
		"Random Goals": { "image": "http://i.imgur.com/VsrwkZZ.png" },
			
		"The Great Rampo": {"image": "http://i.imgur.com/9dgRcWq.png" },
		"Brrreeze Blok": {"image": "http://i.imgur.com/pxViQR9.png" },
		"Trev the Tenteyecle": {"image": "http://i.imgur.com/YqVek8v.png" },
		"I.N.E.P.T.": {"image": "http://i.imgur.com/1JqtEO1.png" },
		"Planette": {"image": "http://i.imgur.com/s4kIB1d.png" },
		"Capital B": {"image": "http://i.imgur.com/raIkhkd.png" }
	},
	
	"modifiers": {
		"Pagies": [
			{ "name": "No Flappy Flight", "difficulty": 4 }
		]
	}
}
